export const PROJECTS: Project[] = [
  {
    id: 1,
    name: "Berger Paints India Ltd – Barrel Scrap Yard Construction – Hindupur, Andhra Pradesh",
    value: "600 Lakhs",
    client: "Berger Paints India Limited",
    category: "Industrial",
    image: IMAGES_PROJECT_1[0],
    images: IMAGES_PROJECT_1,
  },
  {
    id: 2,
    name: "Berger Paints India Ltd – CSR Food Court Construction – Thumakunta, Andhra Pradesh",
    value: "—",
    client: "Berger Paints India Limited",
    category: "Parks / CSR",
    image: IMAGES_PROJECT_2[0],
    images: IMAGES_PROJECT_2,
  },
  {
    id: 3,
    name: "Berger Paints India Ltd – RMS Canopy Extension Work – Hindupur, Andhra Pradesh",
    value: "—",
    client: "Berger Paints India Limited",
    category: "Industrial",
    image: IMAGES_PROJECT_3[0],
    images: IMAGES_PROJECT_3,
  },
  {
    id: 4,
    name: "Sewage Treatment Plant Construction – Hindupur, Andhra Pradesh",
    value: "—",
    client: "Government of Andhra Pradesh",
    category: "Sewage",
    image: IMAGES_PROJECT_4[0],
    images: IMAGES_PROJECT_4,
  },

  // ---------------- GOVERNMENT & INFRASTRUCTURE ----------------

  {
    id: 5,
    name: "Government Tool Room Facility Construction – Gauribidanur Industrial Estate, Karnataka",
    value: "1050 Lakhs",
    client: "Government of Karnataka / NSL",
    category: "Industrial",
  },
  {
    id: 6,
    name: "Upgradation of 35 Slums – Hospet Municipality, Karnataka",
    value: "660 Lakhs",
    client: "IVRCL / Government of Karnataka",
    category: "Mass Housing",
  },
  {
    id: 7,
    name: "Upgradation of 13 Slums – Chitradurga Municipality, Karnataka",
    value: "330 Lakhs",
    client: "IVRCL / Government of Karnataka",
    category: "Mass Housing",
  },
  {
    id: 8,
    name: "Railway Track Construction with Ballast Supply & Laying – Karnataka",
    value: "155 Lakhs",
    client: "Indian Railways (Government of India)",
    category: "Infrastructure",
  },
  {
    id: 9,
    name: "Overhead Sub-Reservoir Construction – Hindupur Constituency, Andhra Pradesh",
    value: "150 Lakhs",
    client: "Government of Andhra Pradesh",
    category: "Water Infrastructure",
  },
  {
    id: 10,
    name: "Ghat Road Construction for Wind Mills – Mundergi, Gadag District, Karnataka",
    value: "350 Lakhs",
    client: "Suzlon Infrastructure Limited",
    category: "Roads & Highways",
  },
  {
    id: 11,
    name: "Ghat Road & Platform Construction for Wind Mill Projects – Karnataka",
    value: "450 Lakhs",
    client: "Barooka Power Corporation",
    category: "Roads & Highways",
  },
  {
    id: 12,
    name: "Canal No.13 Upgradation – Bhadra Canal Project – Shivamoga, Karnataka",
    value: "110 Lakhs",
    client: "IVRCL & GVPR",
    category: "Water Infrastructure",
  },
  {
    id: 13,
    name: "Upgradation of Canals 9C, 7C, 150C & 135C – Bhadra Canal Project, Karnataka",
    value: "350 Lakhs",
    client: "IVRCL & GVPR",
    category: "Water Infrastructure",
  },
  {
    id: 14,
    name: "Overhead Reservoir Construction – Sri Rama Reddy Drinking Water Project, Andhra Pradesh",
    value: "100 Lakhs",
    client: "Larsen & Toubro (L&T)",
    category: "Water Infrastructure",
  },
  {
    id: 15,
    name: "Furnace Building Slabs & Pump Houses Construction – Hindupur, Andhra Pradesh",
    value: "145 Lakhs",
    client: "M.B. Smelters",
    category: "Industrial",
  },
  {
    id: 16,
    name: "Compound Wall & Pump House Construction – Berger Paints – Hindupur, Andhra Pradesh",
    value: "145 Lakhs",
    client: "Berger Paints India Limited",
    category: "Industrial",
  },
  {
    id: 17,
    name: "Industrial Facility Construction – British Paints – Hindupur, Andhra Pradesh",
    value: "140 Lakhs",
    client: "British Paints",
    category: "Industrial",
  },
  {
    id: 18,
    name: "Canteen Building & Expansion Sheds – Wipro Infrastructure",
    value: "150 Lakhs",
    client: "Wipro Enterprises Limited",
    category: "Industrial",
  },
  {
    id: 19,
    name: "Road & Layout Development – KIADB JV Project – Gauribidanur, Karnataka",
    value: "710 Lakhs",
    client: "KIADB (Government of Karnataka)",
    category: "Infrastructure",
  },
  {
    id: 20,
    name: "Industrial Furnace Construction – Tirupati Steels – Hindupur, Andhra Pradesh",
    value: "150 Lakhs",
    client: "Tirupati Steels",
    category: "Industrial",
  },
  {
    id: 21,
    name: "State Highway Construction – Yelburga to Cocoonor – Koppal District, Karnataka",
    value: "1750 Lakhs",
    client: "Government of Karnataka",
    category: "Roads & Highways",
  },
  {
    id: 22,
    name: "Road & Layout Development – KIADB JV Project – Narasapur, Karnataka",
    value: "400 Lakhs",
    client: "KIADB (Government of Karnataka)",
    category: "Infrastructure",
  },
  {
    id: 23,
    name: "Construction of Manufacturing Unit – British Paints – Gollapuram Industrial Area, Hindupur, Andhra Pradesh",
    value: "—",
    client: "British Paints",
    category: "Industrial",
  },
  {
    id: 24,
    name: "Sri Sathya Sai Park Development Work – Supported by Joyalukkas Foundation – Puttaparthi, Andhra Pradesh",
    value: "—",
    client: "Joyalukkas Foundation",
    category: "Parks / CSR",
    image: IMAGES_PROJECT_5[0],
    images: IMAGES_PROJECT_5,
  },
];
